# Created using wingetcreate 1.5.5.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.5.0.schema.json

PackageIdentifier: Garmin.Express
PackageVersion: 7.18.4.0
InstallerLocale: en-US
MinimumOSVersion: 10.0.0.0
InstallerType: burn
Scope: machine
InstallModes:
- interactive
- silent
- silentWithProgress
UpgradeBehavior: install
Installers:
- Architecture: x86
  InstallerUrl: https://download.garmin.com/omt/express/GarminExpress.exe
  InstallerSha256: 3B7D798AD0A8549D8366E79E8AB90D8FDAAEFCE0F4A6BAD3481FB67754787F8E
ManifestType: installer
ManifestVersion: 1.5.0
