# Created using wingetcreate 1.5.5.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.version.1.5.0.schema.json

PackageIdentifier: Garmin.Express
PackageVersion: 7.18.4.0
DefaultLocale: en-US
ManifestType: version
ManifestVersion: 1.5.0
