# Created using wingetcreate 1.5.5.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.5.0.schema.json

PackageIdentifier: OracleCorporation.MySQLWorkbench
PackageVersion: 8.0.34
PackageLocale: en-US
Publisher: Oracle Corporation
PackageName: MySQL Workbench 8.0 CE
License: Proprietary
ShortDescription: MySQL Workbench is a unified visual tool for database architects, developers, and DBAs. MySQL Workbench provides data modeling, SQL development, and comprehensive administration tools for server configuration, user administration, backup, and much more.
ManifestType: defaultLocale
ManifestVersion: 1.5.0
