# Created using wingetcreate 1.2.5.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.4.0.schema.json

PackageIdentifier: Anaplan.ExcelAddin
PackageVersion: 4.4.3.410
PackageLocale: en-US
Publisher: Anaplan
PackageName: ExcelAddin
License: MIT License
ShortDescription: Anaplan series 4 Excel Add-in to access data from Anaplan modules and saved views in Microsoft Excel.
ManifestType: defaultLocale
ManifestVersion: 1.4.0
